<?php

namespace PointWeb\ProductBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
  
      public function findAll()
    {
        return $this->findBy(array(), array('createDate' => 'DESC'));
    }
  
      public function findRecommended()
    {
        $q = $this->createQueryBuilder('n');
        $q->addOrderBy('n.createDate', 'DESC')
            ->setMaxResults(4);
        $res = $q->getQuery();
        return $res->getResult();
    }
  
      public function findFirst()
    {
        $q = $this->createQueryBuilder('n');
        $q->addOrderBy('n.createDate', 'DESC')
            ->setMaxResults(1);
        $res = $q->getQuery();
        return $res->getResult();
    }
  
}
